body:
- type: input
  id: suggestion
  attributes:
    label: Suggestion
    description: "<img src=x onerror=alert(1)><svg></svg>"
    value: "value"
    placeholder: "placeholder"
  validations:
    required: false
